#!/bin/bash
rm replica.txt
rm Lamport.txt
rm output_alpha.txt
java AggregationServer 4567 >> trash.txt &
sleep 2
java ContentServer AggregationServer:4567 sample.txt 1 >> Lamport.txt &
java ContentServer AggregationServer:4567 sample2.txt 2 >> Lamport.txt &
java ContentServer AggregationServer:4567 sample3.txt 3 >> Lamport.txt &
sleep 2
java GETClient AggregationServer:4567 >> output_alpha.txt
pkill -f 'AggregationServer'
pkill -f 'ContentServer AggregationServer:4567 sample.txt 1'
pkill -f 'ContentServer AggregationServer:4567 sample2.txt 2'
echo "Synchronization and Lamport clock test and demonstration"
echo "Test complete - please check Lamport.txt and output_alpha.txt"
rm trash.txt


#this script is to show that the code is synchronized.
#by not sleeping in between each execution of the 3 ContentServer processes, I can't guarantee their
#exact order of execution by the OS. However, their output, although random, is never intertwined in the sense
#that each process executes in full (their content is uploaded in a single chunk), rather than being mixed
#due to threads being preempted in middle of critcal section etc.

#this means that no matter what order these processes are started and executed, whichever starts first will
#always execute in full, followed by the next process, then the last.
#this is reflected in the output_alpha.txt file generated, as if it's compared with the source txt files passed
#into each ContentServer, the entries of each source txt file are always one continuous chunk after another with no entries dispersed 
#between each other randomly.

#The lamport.txt file will show that the lamport clocks of each process are correct and maintained in the correct
#order that they execute (highest LC for the last executed CS which would be the last entries added to output_alpha.txt)

#NOTE that this script will remove old output files generated by this script so it's less confusing (lines 3 and 4 remove old files). If they do not exist, script will print "No such file or director"
#but will continue as normal.

#NOTE - trash.txt is just to redirect output from AS or CS, since they are not important in this test and do not need to be printed to CLI.